### ISSUE TITLE
Improve the sign in page

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/cloud-hosted-guides#195]
- [x] The height of the email and password text fields are too much. They can be thinner.
- [x] The sign in button font is too big too
- [x] the font size of all text should be same except the title
- [x] The title "Sign in" and the sign in button look duplicated
 
![Screen Shot 2020-12-22 at 1 13 25 PM](https://user-images.githubusercontent.com/29576299/102919897-aa9a1400-4457-11eb-9171-2f193a6ea1ad.png)

**Comment by jamiecoleman92** [comment]
Hey @gkwan-ibm 
From what I can see the above matches what we agreed upon in the design. Do you want us to make changes to the design?

Here is the agreed upon design:
![image](https://user-images.githubusercontent.com/14291840/104335848-aeb3d180-54eb-11eb-9189-37a26e4b6a7b.png)

**Comment by gkwan-ibm** [comment]
Based on the actual login page, 
- I still feel the text font for "Email", "The email address ....", "Password" is a bit small. Can make them bigger as the font of "First time here?" or "Remember me"?
- I suggest the title to be "Sign in to Open Liberty SkillsNetwork" instead of just "Sign In"

**Comment by austin0** [comment]
Changed title to 'Access Cloud Hosted Guides' and made text slightly larger.

**Comment by gkwan-ibm** [comment]
- will be addressed by SN team

**Comment by gkwan-ibm** [comment]
close
- addressed listed issues
-  other login page issues will by #314 #341
